# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            "Valentin Peretroukhin"
tagline:          "Valentin's Homepage"
description:      'Ph.D. student in <a href="http://stars.utias.utoronto.ca">autonomous mobile robotics</a>. Wannabe philosopher. Technology lover.  Sports geek.'
url:              http://valentinp.com
baseurl:          /

author:
  name:           'Valentin Peretroukhin'
  url:            https://twitter.com/valentinp
