# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            "Valentin Peretroukhin"
tagline:          "Valentin's Homepage" 
description:      'Ph.D. student in <a href="http://stars.utias.utoronto.ca" target="_blank">autonomous mobile robotics</a>. Aviation enthusiast. Techmology lover. Sports geek.'
url:              http://valentinp.com
baseurl:          /

author:
  name:           'Valentin Peretroukhin'
  url:            https://twitter.com/valentinp

paginate:         5

